<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AuthTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Test root redirects to login.
     */
    public function test_root_redirects_to_login(): void
    {
        $response = $this->get('/');
        $response->assertRedirect('/login');
    }

    /**
     * Test guest cannot access admin dashboard.
     */
    public function test_guest_cannot_access_admin_dashboard(): void
    {
        $response = $this->get('/admin/dashboard');
        $response->assertRedirect('/login');
    }

    /**
     * Test admin can login and access admin dashboard.
     */
    public function test_admin_can_login_and_access_admin_dashboard(): void
    {
        $admin = User::factory()->create([
            'email' => 'admin@sppg.go.id',
            'role' => 'admin',
        ]);

        $response = $this->post('/login', [
            'email' => 'admin@sppg.go.id',
            'password' => 'password', // generated by factory default hasher or seeding
        ]);

        // Note: Default UserFactory uses 'password' as hashed password.
        $response->assertRedirect('/admin/dashboard');
        $this->assertAuthenticatedAs($admin);
    }

    /**
     * Test instansi can login and access instansi dashboard.
     */
    public function test_instansi_can_login_and_access_instansi_dashboard(): void
    {
        $instansi = User::factory()->create([
            'email' => 'sd@sppg.go.id',
            'role' => 'instansi',
        ]);

        $response = $this->post('/login', [
            'email' => 'sd@sppg.go.id',
            'password' => 'password',
        ]);

        $response->assertRedirect('/instansi/dashboard');
        $this->assertAuthenticatedAs($instansi);
    }

    /**
     * Test admin cannot access instansi dashboard.
     */
    public function test_admin_cannot_access_instansi_dashboard(): void
    {
        $admin = User::factory()->create([
            'role' => 'admin',
        ]);

        $response = $this->actingAs($admin)->get('/instansi/dashboard');

        $response->assertRedirect('/admin/dashboard');
        $response->assertSessionHas('error');
    }

    /**
     * Test instansi cannot access admin dashboard.
     */
    public function test_instansi_cannot_access_admin_dashboard(): void
    {
        $instansi = User::factory()->create([
            'role' => 'instansi',
        ]);

        $response = $this->actingAs($instansi)->get('/admin/dashboard');

        $response->assertRedirect('/instansi/dashboard');
        $response->assertSessionHas('error');
    }
}
